### ISSUE TITLE
configTICK_RATE_HZ not honoured

### ISSUE THREAD

**Issue by Steve-Squires** [discord-intech/FreeRTOS-Teensy4#1]
Hi Julian - great work on this port. 

However, changing the configTICK_RATE_HZ seems to have no effect on the actual scheduler.

In other words, the LED blink rate in the example program changes when the tick rate constant is changed.

Thanks,
Steve

**Comment by juliandesvignes** [comment]
I see the problem, I forgot to set the proper timer value for the ISR. I will fix this on Monday. Sorry for the inconvenience.

**Comment by Steve-Squires** [comment]
Thank you!

**Comment by juliandesvignes** [comment]
The latest commits should fix the issue, I tested it with the Blink example. If you are using PlatformIO, make sure your `Teensy4FreeRTOSConfig.h` / `Teensy4FreeRTOSConfig_addition.h` are in the `include` dir of your project and that this lib is cloned in the `lib` folder of your project.

Just please know that I am using the external clock for systicking (this allows to adjust the frequency of the CPU on the fly without having any time scaling problems), making the maximum tick rate at 100 kHz. 

If you have any other problem related or not to ticking, please feel free to reopen or open a new issue.
